Code/mytest_1219/mytest_1219/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin_2018103297/', admin.site.urls),
    path('test1219/', include('test1219.urls')),
]

Code/mytest_1219/test1219/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'test1219'
urlpatterns = [
    path('', views.index, name='index'),  # /polls/
    path('maps/', views.maps, name='maps')
]

Code/mytest_1219/test1219/models.py
from django.db import models

class Wifi_2018103297(models.Model):
    installLocationDetail = models.CharField(max_length=200)
    category = models.CharField(max_length=200)
    addressDong = models.CharField(max_length=200)
    latitude = models.FloatField(default=0.0)
    longitude = models.FloatField(default=0.0)

    def __str__(self):
        return self.name_text

Code/mytest_1219/test1219/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from urllib.parse import urlencode
from urllib.request import urlopen
import json
import csv
import math

from test1219.models import Wifi_2018103297
from django.views.decorators.csrf import csrf_exempt

#@csrf_exempt
def index(request):
    return render(request, 'test1219/index.html', None)

#@csrf_exempt
def maps(request):
    jejuelec = request.POST.get('jejuelec')
    if(jejuelec==""):
        return render(request, 'test1219/index.html', {
            'error_message': "입력하지 않으셨습니다. 다시 입력 부탁드립니다.",
                })

    else:
        print(jejuelec)
        url = 'https://gw.jejudatahub.net/api/proxy/c5ef63523b1611e9ab958f5bbd84cea8/'


        input_json = {'addressDong': jejuelec}# 'name': '노형동주민센터'}#원하는 데이터 조건 설정, 필수 ㅔ데이터는 꼭 넣어야 한다, 받는 걸 선택할 땐, json
        # ,'addressDong': jejuelec
        # 'latitude': '33.483098',
        # 'longitude': '126.477231'}
        queryParams = '?' + urlencode(input_json)  # 키랑 url을 연결시키는 부분

        input_url = url + 'b9f1e4a56cd611eaa1d5aff3bc30f288' + queryParams  # api에 넣을 url 완성
        print(input_url)

        response_body = urlopen(input_url).read().decode('utf-8')  # 받은 응답 변수에 넣기
        print(response_body)

        json_data = json.loads(response_body)  # 응답 json으로 만들기

        if(json_data['totCnt']==0):
            return render(request, 'test1219/index.html', {
                'error_message': "없는 장소입니다. 다시 입력해주십시오",
            })
        items = json_data['data']  # 데이터에서 Data 안에 들어 있는 것 보기

        for data in items:  # data에 있는걸 itmes 만큼 출력해라
            onerow = []
            onerow.append(data['name'])
            onerow.append(data['longitude'])
            onerow.append(data['latitude'])

        name = onerow[0]
        longitude = onerow[1]
        latitude = onerow[2]

        return render(request, 'test1219/maps.html', {'name': name, 'longitude': longitude, 'latitude': latitude})

Code/mytest_1219/test1219/templates/test1219/index.html
//사용자에게 검색할 지역에 대한 정보를 받는 페이지 입니다.

<h1>경영정보학과 2022학년도 1학기 캡스톤</h1>
<h2>주차 가능한 맛집 보기</h2>
{{error_message}}
<h3>찾아보길 원하는 지역을 입력해주세요.</h3>
<form action="{% url 'test1219:maps'%}" method=POST>{% csrf_token %}
    <input type=text placeholder="동네 이름을 입력해주세요" name="jejuelec">
    <br>
    <button type=submit >지도에서 보기</button>
</form>

Code/mytest_1219/test1219/templates/test1219/maps.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>지도 생성하기</title>
    <style>
.label {margin-bottom: 96px;}
.label * {display: inline-block;vertical-align: top;}
.label .left {background: url("https://t1.daumcdn.net/localimg/localimages/07/2011/map/storeview/tip_l.png") no-repeat;display: inline-block;height: 24px;overflow: hidden;vertical-align: top;width: 7px;}
.label .center {background: url(https://t1.daumcdn.net/localimg/localimages/07/2011/map/storeview/tip_bg.png) repeat-x;display: inline-block;height: 24px;font-size: 12px;line-height: 24px;}
.label .right {background: url("https://t1.daumcdn.net/localimg/localimages/07/2011/map/storeview/tip_r.png") -1px 0  no-repeat;display: inline-block;height: 24px;overflow: hidden;width: 6px;}
</style>


</head>
<body>
<!-- 지도를 표시할 div 입니다 -->
<div id="map" style="width:100%;height:400px;"></div>
<p>{{name}} 공공 와이파이 위치 입니다.</p>
<p>위도 : {{longitude}}, 경도 : {{latitude}}</p>
<br>
<p><em>클릭하시면 위도, 경도를 알려드려요</em></p>
<p id="result"></p>



<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=d9349d629a50a621fea0d42c6faaa2ce"></script>
<script>
var mapContainer = document.getElementById('map'), // 지도를 표시할 div
    mapOption = {
        center: new kakao.maps.LatLng({{latitude}}, {{longitude}}), // 지도의 중심좌표
        level: 3 // 지도의 확대 레벨
    };


var positions = [
    {
        title: '{{name}}',
        latlng: new kakao.maps.LatLng({{latitude}}, {{longitude}})
    }
];

// 마커 이미지의 이미지 주소입니다


var imageSrc = "https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/marker_red.png";

for (var i = 0; i < positions.length; i ++) {

    // 마커 이미지의 이미지 크기 입니다
    var imageSize = new kakao.maps.Size(24, 35);

    // 마커 이미지를 생성합니다
    var markerImage = new kakao.maps.MarkerImage(imageSrc, imageSize);

    // 마커를 생성합니다
    var marker = new kakao.maps.Marker({
        map: map, // 마커를 표시할 지도
        position: positions[i].latlng, // 마커를 표시할 위치
        title : positions[i].title, // 마커의 타이틀, 마커에 마우스를 올리면 타이틀이 표시됩니다
        image : markerImage // 마커 이미지
    });
}

// 커스텀 오버레이에 표시할 내용입니다
// HTML 문자열 또는 Dom Element 입니다
var content = '<div class ="label"><span class="left"></span><span class="center">전기차충전소!</span><span class="right"></span></div>';

// 커스텀 오버레이가 표시될 위치입니다
var position = new kakao.maps.LatLng({{latitude}} , {{longitude}});

// 커스텀 오버레이를 생성합니다
var customOverlay = new kakao.maps.CustomOverlay({
    position: position,
    content: content
});

// 커스텀 오버레이를 지도에 표시합니다
customOverlay.setMap(map);



</script>
<a href="{% url 'test1219:index' %}">home</a>
</body>
</html>